version: '3.3' # use your version
services:
  jenkins-2:
    image: jenkins_micka:1.0.0 # use your tag name
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - '8080:8080'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vault.key:/root/vault.key
    environment:
      - ANSIBLE_VAULT_PASSWORD_FILE=/root/vault.key
volumes:
  jenkins_data:
    external: true

